### ISSUE TITLE
XML Validation of view/adminhtml/ui_component/cms_page_form.xml failed

### ISSUE THREAD

**Issue by m-schreiber** [magesuite/opengraph#1]
When in Developer-Mode, the XML-Schema-Validation for `view/adminhtml/ui_component/cms_page_form.xml` fails with
```
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/vendor/creativestyle/magesuite-opengraph/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 9
```
Removing the following Lines fixes the Problem:
https://github.com/magesuite/opengraph/blob/92122e0d80de6358d259e7175af19922478acfb7/view/adminhtml/ui_component/cms_page_form.xml#L9 to
https://github.com/magesuite/opengraph/blob/92122e0d80de6358d259e7175af19922478acfb7/view/adminhtml/ui_component/cms_page_form.xml#L13 and
https://github.com/magesuite/opengraph/blob/92122e0d80de6358d259e7175af19922478acfb7/view/adminhtml/ui_component/cms_page_form.xml#L56

**Comment by berbua** [comment]
Hello @m-schreiber , please be informed that issue has been fixed with https://github.com/magesuite/opengraph/commit/e5349e77803e57d8d650280699a93b59945d7099
